#
# Copyright 2021, Matthew Ahrenstein, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matt@ahrenstein.com
#
# See LICENSE

version: '2'
services:
  bots-db:
    container_name: bots-db
    image: mongo:3.6
    volumes:
      - ./config/db-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: bots
      MONGO_INITDB_ROOT_PASSWORD: buythedip
    expose:
      - 27017
    ports:
      - "127.0.0.1:27017:27017"
    restart: always
  gemini-eth:
    links:
     - bots-db
    container_name: gemini-eth
    image: local/dipbot:test
    build: ./
    volumes:
      - ./config:/config
    command: [ "python", "-u", "/app/cryptodip_bot.py", "-c", "/config/gemini-config.json", "-d"]
    restart: always
  coinbase-eth:
    links:
      - bots-db
    container_name: coinbase-eth
    image: local/dipbot:test
    build: ./
    volumes:
      - ./config:/config
    command: [ "python", "-u", "/app/cryptodip_bot.py", "-c", "/config/coinbase-config.json", "-d"]
    restart: always
