name: 'Deploy container to named tag'

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_KEY }}
      - name: Build the Docker image
        run: |
          echo "Building container..."
          docker build -f Dockerfile -t ahrenstein/cryptodip-bot:${GITHUB_REF/refs\/tags\//} .
          echo "Pushing container to Docker Hub..."
          docker push ahrenstein/cryptodip-bot:${GITHUB_REF/refs\/tags\//}
          echo "Done!"
